---
#Utiliza telnet

# R38:
#   hostname: 192.168.100.121
#   port: 33318
#   platform: cisco_ios_telnet
#   username: rggt0001
#   password: Ruddy2002
#   data:
#     napalm_driver: ios
#   groups:
#     - Routers

#Utiliza Telnet

# SW14:
#   hostname: 192.168.100.121
#   port: 33294
#   platform: cisco_ios_telnet
#   username: rggt0001
#   password: Ruddy2002
#   data:
#     napalm_driver: ios
#   groups:
#     - Switches
# ARISTA:
#   hostname: 192.168.100.121
#   port: 33335
#   platform: arista_eos_telnet
#   username: Arista
#   password: arista
#   groups:
#     - Switches
#   connection_options:
#     napalm:
#       extras:
#         optional_args:
#           transport: "telnet"

Sandbox_Cisco_XE:
  hostname: devnetsandboxiosxe.cisco.com
  port: 22
  platform: ios
  username: admin
  password: C1sco12345
  groups:
    - Switches

#No admite revision de archivos

# Sandbox_Cisco_XR:
#   hostname: sandbox-iosxr-1.cisco.com
#   port: 22
#   platform: ios
#   username: admin
#   password: C1sco12345
#   groups:
#     - Switches
